printWidth: 110
plugins: ['@trivago/prettier-plugin-sort-imports']
importOrder: ['^@domain/(.*)$', '^@infrastructure/(.*)$', '^@api/(.*)$', '^[./]']
importOrderSeparation: true
importOrderParserPlugins: ['typescript', 'decorators-legacy']
importOrderSortSpecifiers: true
singleQuote: true
semi: true
